### ISSUE TITLE
when training  unitree_g1 and  replace the defaut motion_file with 0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses.pkl ,  after produce Humanoid_00001500.pth，and then it occurs an torch.OutOfMemoryError: CUDA out of memory error

### ISSUE THREAD

**Issue by dbdxnuliba** [ZhengyiLuo/PHC#101]
Hello,when training  unitree_g1 and  replace the defaut motion_file with 0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses.pkl ,  after produce Humanoid_00001500.pth，and then it occurs an torch.OutOfMemoryError: CUDA out of memory error, the following is the detail: 
```
(phc) rob@lenovo-ThinkStation-PX:~/PHC$ python phc/run_hydra.py project_name=Robot_IM robot=unitree_g1 env=env_im_g1_phc env.motion_file=sample_data/0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses.pkl learning=im_pnn_big exp_name=unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses sim=robot_sim control=robot_control learning.params.network.space.continuous.sigma_init.val=-1.7 
Importing module 'gym_38' (/home/rob/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/rob/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.4.1+cu121
Device count 3
/home/rob/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/rob/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/rob/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2024-11-25 16:58:34,556 - INFO - logger - logger initialized
MOVING MOTION DATA TO GPU, USING CACHE: False
MOVING MOTION DATA TO GPU, USING CACHE: False
MOVING MOTION DATA TO GPU, USING CACHE: False
Importing module 'rlgpu_38' (/home/rob/isaacgym/python/isaacgym/_bindings/linux-x86_64/rlgpu_38.so)
2024-11-25 16:58:36,527 - DEBUG - Popen(['git', 'version'], cwd=/home/rob/PHC, stdin=None, shell=False, universal_newlines=False)
2024-11-25 16:58:36,544 - DEBUG - Popen(['git', 'version'], cwd=/home/rob/PHC, stdin=None, shell=False, universal_newlines=False)
2024-11-25 16:58:36,566 - DEBUG - Trying paths: ['/home/rob/.docker/config.json', '/home/rob/.dockercfg']
2024-11-25 16:58:36,566 - DEBUG - No config file found
2024-11-25 16:58:36,673 - DEBUG - Setting JobRuntime:name=UNKNOWN_NAME
2024-11-25 16:58:36,673 - DEBUG - Setting JobRuntime:name=run_hydra
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: nuliguangxiao-yang. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.6
wandb: Run data is saved locally in /home/rob/PHC/wandb/run-20241125_165838-drujpxsn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run twilight-puddle-9
wandb: ⭐️ View project at https://wandb.ai/nuliguangxiao-yang/Robot_IM
wandb: 🚀 View run at https://wandb.ai/nuliguangxiao-yang/Robot_IM/runs/drujpxsn
wandb: WARNING Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
torch_deterministic: False
torch_deterministic: False
torch_deterministic: False
Setting seed: 0
Started to train
/home/rob/anaconda3/envs/phc/lib/python3.8/site-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
JointSpec type free not yet supported!
Cylinder is not natively supported, tesellated mesh will be used
Cylinder is not natively supported, tesellated mesh will be used
/home/rob/isaacgym/python/isaacgym/torch_utils.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(x, dtype=dtype, device=device, requires_grad=requires_grad)
Humanoid Weights [32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085, 32.238920867443085]
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
Warning: DOF limits are the same
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 82.84it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 73877.45it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 84.78it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 75105.85it/s]

****************************** Current motion keys ******************************
Sampling motion: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0], device='cuda:0')
['0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses'] .....
*********************************************************************************

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3072/3072 [12:34<00:00,  4.07it/s]
0it [00:00, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3072/3072 [00:01<00:00, 2464.98it/s]
Loaded 3072 motions with a total length of 132305.906s and 3972096 frames.
/home/rob/anaconda3/envs/phc/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
RL device:  cuda:0
3072
37
1480
0
Box(-1.0, 1.0, (37,), float32) Box(-inf, inf, (1480,), float32)
Env info:
{'action_space': Box(-1.0, 1.0, (37,), float32), 'observation_space': Box(-inf, inf, (1480,), float32), 'amp_observation_space': Box(-inf, inf, (990,), float32), 'enc_amp_observation_space': Box(-inf, inf, (990,), float32), 'task_obs_size': 0}
/home/rob/anaconda3/envs/phc/lib/python3.8/site-packages/rl_games/common/a2c_common.py:175: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(enabled=self.mixed_precision)
RunningMeanStd:  (1,)
RunningMeanStd:  (1480,)
build mlp: 1480
build mlp: 1480
build mlp: 990
build mlp: 1480
build mlp: 1480
build mlp: 1480
sigma
critic_mlp.0.weight
critic_mlp.0.bias
critic_mlp.2.weight
critic_mlp.2.bias
critic_mlp.4.weight
critic_mlp.4.bias
critic_mlp.6.weight
critic_mlp.6.bias
critic_mlp.8.weight
critic_mlp.8.bias
critic_mlp.10.weight
critic_mlp.10.bias
value.weight
value.bias
mu.weight
mu.bias
_disc_mlp.0.weight
_disc_mlp.0.bias
_disc_mlp.2.weight
_disc_mlp.2.bias
_disc_logits.weight
_disc_logits.bias
pnn.actors.0.0.weight
pnn.actors.0.0.bias
pnn.actors.0.2.weight
pnn.actors.0.2.bias
pnn.actors.0.4.weight
pnn.actors.0.4.bias
pnn.actors.0.6.weight
pnn.actors.0.6.bias
pnn.actors.0.8.weight
pnn.actors.0.8.bias
pnn.actors.0.10.weight
pnn.actors.0.10.bias
pnn.actors.0.12.weight
pnn.actors.0.12.bias
pnn.actors.1.0.weight
pnn.actors.1.0.bias
pnn.actors.1.2.weight
pnn.actors.1.2.bias
pnn.actors.1.4.weight
pnn.actors.1.4.bias
pnn.actors.1.6.weight
pnn.actors.1.6.bias
pnn.actors.1.8.weight
pnn.actors.1.8.bias
pnn.actors.1.10.weight
pnn.actors.1.10.bias
pnn.actors.1.12.weight
pnn.actors.1.12.bias
pnn.actors.2.0.weight
pnn.actors.2.0.bias
pnn.actors.2.2.weight
pnn.actors.2.2.bias
pnn.actors.2.4.weight
pnn.actors.2.4.bias
pnn.actors.2.6.weight
pnn.actors.2.6.bias
pnn.actors.2.8.weight
pnn.actors.2.8.bias
pnn.actors.2.10.weight
pnn.actors.2.10.bias
pnn.actors.2.12.weight
pnn.actors.2.12.bias
RunningMeanStd:  (1,)
RunningMeanStd:  (990,)
/home/rob/PHC/phc/learning/amp_agent.py:601: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=self.mixed_precision):
/home/rob/anaconda3/envs/phc/lib/python3.8/site-packages/torch/autograd/graph.py:769: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 1	rwd: 2.1	fps_step: 23360.7	fps_total: 14060.0	ep_time:7.0	frame: 98304	eps_len: 4.2
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 2	rwd: 2.1	fps_step: 24131.8	fps_total: 14308.6	ep_time:6.9	frame: 196608	eps_len: 4.3
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 3	rwd: 2.1	fps_step: 20839.1	fps_total: 13007.0	ep_time:7.6	frame: 294912	eps_len: 4.2
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 4	rwd: 2.2	fps_step: 20874.5	fps_total: 12966.8	ep_time:7.6	frame: 393216	eps_len: 4.3
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 5	rwd: 2.2	fps_step: 21459.0	fps_total: 13213.0	ep_time:7.5	frame: 491520	eps_len: 4.3
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 6	rwd: 2.2	fps_step: 21557.1	fps_total: 13202.3	ep_time:7.5	frame: 589824	eps_len: 4.3
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 7	rwd: 2.2	fps_step: 22296.5	fps_total: 13421.9	ep_time:7.3	frame: 688128	eps_len: 4.4
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 8	rwd: 2.2	fps_step: 23270.1	fps_total: 13739.4	ep_time:7.2	frame: 786432	eps_len: 4.4
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 9	rwd: 2.2	fps_step: 24859.4	fps_total: 14186.3	ep_time:7.0	frame: 884736	eps_len: 4.4
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 10	rwd: 2.2	fps_step: 24587.4	fps_total: 14084.5	ep_time:7.0	frame: 983040	eps_len: 4.4
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 11	rwd: 2.3	fps_step: 24714.9	fps_total: 14067.1	ep_time:7.0	frame: 1081344	eps_len: 4.5
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 12	rwd: 2.3	fps_step: 22154.5	fps_total: 13165.0	ep_time:7.5	frame: 1179648	eps_len: 4.6
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 13	rwd: 2.4	fps_step: 24496.2	fps_total: 13907.9	ep_time:7.1	frame: 1277952	eps_len: 4.6
unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 14	rwd: 2.4	fps_step: 26249.4	fps_total: 14407.1	ep_time:6.8	frame: 1376256	eps_len: 4.7



unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses-Ep: 1499	rwd: 549.9	fps_step: 25371.8	fps_total: 13901.5	ep_time:7.1	frame: 147357696	eps_len: 1010.1
=> saving checkpoint 'output/HumanoidIm/unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses/Humanoid.pth'
=> saving checkpoint 'output/HumanoidIm/unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses/Humanoid_00001500.pth'
############################ Evaluation ############################
0it [00:00, ?it/s]
****************************** Current motion keys ******************************
Sampling motion: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0], device='cuda:0')
['0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses' '0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses'] .....
*********************************************************************************

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3072/3072 [09:49<00:00,  5.21it/s]
0it [00:00, ?it/s]█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3072/3072 [09:49<00:00,  5.17it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3072/3072 [00:01<00:00, 2683.80it/s]
Error executing job with overrides: ['project_name=Robot_IM', 'robot=unitree_g1', 'env=env_im_g1_phc', 'env.motion_file=sample_data/0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses.pkl', 'learning=im_pnn_big', 'exp_name=unitree_g1_DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_poses', 'sim=robot_sim', 'control=robot_control', 'learning.params.network.space.continuous.sigma_init.val=-1.7']
Traceback (most recent call last):
  File "phc/run_hydra.py", line 337, in main
    runner.run(cfg)
  File "/home/rob/anaconda3/envs/phc/lib/python3.8/site-packages/rl_games/torch_runner.py", line 139, in run
    self.run_train()
  File "/home/rob/anaconda3/envs/phc/lib/python3.8/site-packages/rl_games/torch_runner.py", line 125, in run_train
    agent.train()
  File "/home/rob/PHC/phc/learning/common_agent.py", line 165, in train
    eval_info = self.eval()
  File "/home/rob/PHC/phc/learning/im_amp.py", line 179, in eval
    humanoid_env.begin_seq_motion_samples()
  File "/home/rob/PHC/phc/env/tasks/humanoid_im.py", line 473, in begin_seq_motion_samples
    self._motion_lib.load_motions(skeleton_trees=self.skeleton_trees, gender_betas=self.humanoid_shapes.cpu(), limb_weights=self.humanoid_limb_and_weights.cpu(), random_sample=False, start_idx=self.start_idx)
  File "/home/rob/PHC/phc/utils/motion_lib_real.py", line 205, in load_motions
    self.gvs = torch.cat([m.global_velocity for m in motions], dim=0).float().to(self._device)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.69 GiB. GPU 0 has a total capacity of 44.52 GiB of which 4.19 MiB is free. Including non-PyTorch memory, this process has 44.49 GiB memory in use. Of the allocated memory 35.96 GiB is allocated by PyTorch, and 1.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by YechenZhou** [comment]
I solved this problem when I modified the value of num_envs to 1024 in ~/PHC/phc/data/cfg/env/env_im_g1_phc.yaml file. Hope this helps. @dbdxnuliba

**Comment by dbdxnuliba** [comment]
thank

> I solved this problem when I modified the value of num_envs to 1024 in ~/PHC/phc/data/cfg/env/env_im_g1_phc.yaml file. Hope this helps. @dbdxnuliba

thanks, I'll have a try
